# Maven
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(build.sourcesdirectory)/azurecosmos/target'
    Contents: '**'
    TargetFolder: '- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Below will build the image and push it to azure container registry

      cd /tmp/ycsb
      tar xfvz ycsb-azurecosmos-binding-0.18.0-SNAPSHOT.tar.gz
      cp run.sh ycsb-azurecosmos-binding-0.18.0-SNAPSHOT/
      cp azurecosmos.properties ycsb-azurecosmos-binding-0.18.0-SNAPSHOT/
      
      docker build . -t ycsb-azurecosmos
      
      az acr login --name $(ContainerRegistryName) -u $(ContainerRegistryUserName) -p $(ContainerRegistryPwd)
      
      docker tag ycsb-azurecosmos $(ContainerRegistryUrl)/ycsb-azurecosmos
      
      docker push $(ContainerRegistryUrl)/ycsb-azurecosmos
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
